import type { AgentWorkflow, TraceArtifact, TraceEvent } from "../types/workflow";
import { createPortableWorkflow, createTraceSummary } from "./schema";

export type FrameworkExport = {
  filename: string;
  language: "python" | "json";
  content: string;
  warnings: string[];
};

export type TraceBundleFile = {
  path: string;
  mediaType: string;
  content: string;
};

export type TraceBundle = {
  schema: "agentdesk.trace-bundle.v1";
  createdAt: string;
  workflowId: string;
  files: TraceBundleFile[];
};

export function createLangGraphExport(workflow: AgentWorkflow): FrameworkExport {
  const portable = createPortableWorkflow(workflow);
  const warnings = collectAdapterWarnings(workflow);
  const graphLiteral = JSON.stringify(portable, null, 2);

  return {
    filename: `${workflow.id}.langgraph.py`,
    language: "python",
    warnings,
    content: [
      "\"\"\"Generated by AgentDesk. Review tools, credentials, and side effects before running.\"\"\"",
      "from typing import TypedDict, Any",
      "from langgraph.graph import StateGraph, END",
      "",
      "WORKFLOW = " + graphLiteral,
      "",
      "class AgentDeskState(TypedDict, total=False):",
      "    inputs: dict[str, Any]",
      "    outputs: dict[str, Any]",
      "    trace: list[dict[str, Any]]",
      "",
      "def make_step(node):",
      "    def step(state: AgentDeskState):",
      "        trace = list(state.get('trace', []))",
      "        trace.append({'node_id': node['id'], 'label': node['label'], 'provider': node.get('provider')})",
      "        return {**state, 'trace': trace}",
      "    return step",
      "",
      "graph = StateGraph(AgentDeskState)",
      "for node in WORKFLOW['nodes']:",
      "    graph.add_node(node['id'], make_step(node))",
      "",
      "for edge in WORKFLOW['edges']:",
      "    graph.add_edge(edge['source'], edge['target'])",
      "",
      "start = WORKFLOW['nodes'][0]['id'] if WORKFLOW['nodes'] else END",
      "graph.set_entry_point(start)",
      "for node in WORKFLOW['nodes']:",
      "    if not any(edge['source'] == node['id'] for edge in WORKFLOW['edges']):",
      "        graph.add_edge(node['id'], END)",
      "",
      "app = graph.compile()"
    ].join("\n")
  };
}

export function createCrewAiExport(workflow: AgentWorkflow): FrameworkExport {
  const portable = createPortableWorkflow(workflow);
  const warnings = collectAdapterWarnings(workflow);
  const tasks = portable.nodes
    .map((node) => ({
      id: node.id,
      description: node.promptTemplate ?? node.label,
      expected_output: `${node.label} output`,
      agent: node.provider ?? node.kind
    }));

  return {
    filename: `${workflow.id}.crewai.py`,
    language: "python",
    warnings,
    content: [
      "\"\"\"Generated by AgentDesk. Review tools, credentials, and side effects before running.\"\"\"",
      "from crewai import Agent, Crew, Task",
      "",
      "TASK_DEFS = " + JSON.stringify(tasks, null, 2),
      "",
      "agents = {}",
      "for task in TASK_DEFS:",
      "    agents.setdefault(",
      "        task['agent'],",
      "        Agent(role=task['agent'], goal=f\"Run {task['agent']} steps\", backstory='Generated from AgentDesk')",
      "    )",
      "",
      "tasks = [",
      "    Task(description=task['description'], expected_output=task['expected_output'], agent=agents[task['agent']])",
      "    for task in TASK_DEFS",
      "]",
      "",
      "crew = Crew(agents=list(agents.values()), tasks=tasks)",
      "# result = crew.kickoff()"
    ].join("\n")
  };
}

export function createTraceBundle(workflow: AgentWorkflow, trace: TraceEvent[]): TraceBundle {
  const summary = createTraceSummary(trace);
  const files: TraceBundleFile[] = [
    {
      path: "manifest.json",
      mediaType: "application/json",
      content: JSON.stringify(
        {
          workflow: createPortableWorkflow(workflow),
          traceSummary: summary,
          events: trace.map((event) => ({
            id: event.id,
            nodeId: event.nodeId,
            status: event.status,
            artifactCount: event.artifacts?.length ?? 0
          }))
        },
        null,
        2
      )
    },
    ...trace.flatMap((event) => artifactFiles(event))
  ];

  return {
    schema: "agentdesk.trace-bundle.v1",
    createdAt: new Date().toISOString(),
    workflowId: workflow.id,
    files
  };
}

function artifactFiles(event: TraceEvent): TraceBundleFile[] {
  return (event.artifacts ?? []).map((artifact) => ({
    path: safeBundlePath(event, artifact),
    mediaType: mediaTypeForArtifact(artifact),
    content: artifact.content
  }));
}

function safeBundlePath(event: TraceEvent, artifact: TraceArtifact) {
  const eventSlug = slug(event.nodeLabel || event.nodeId);
  const artifactSlug = slug(artifact.name || artifact.id);
  const extension =
    artifact.type === "json"
      ? "json"
      : artifact.type === "markdown"
        ? "md"
        : artifact.type === "screenshot"
          ? "svg"
          : "log";

  return `events/${slug(event.id)}-${eventSlug}/${artifactSlug}.${extension}`;
}

function mediaTypeForArtifact(artifact: TraceArtifact) {
  switch (artifact.type) {
    case "json":
      return "application/json";
    case "markdown":
      return "text/markdown";
    case "screenshot":
      return "image/svg+xml";
    default:
      return "text/plain";
  }
}

function collectAdapterWarnings(workflow: AgentWorkflow) {
  const warnings: string[] = [];

  for (const node of workflow.nodes) {
    if (node.data.provider === "mcp" || node.data.provider === "local") {
      warnings.push(`${node.data.label}: map local/MCP side effects to explicit tools before production use.`);
    }

    if (node.data.config && Object.keys(node.data.config).length > 0) {
      warnings.push(`${node.data.label}: review config values and replace placeholders with external secrets.`);
    }
  }

  return [...new Set(warnings)];
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "item";
}
